language: go
go:
  - 1.3

install:
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
