language: go
sudo: false
go:
- 1.4

services:
- redis-server

install:
- go get -d -v ./...
- go get github.com/onsi/ginkgo
- go get github.com/onsi/gomega
- go install github.com/onsi/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
